<?php

namespace Modules\Admin\Transformers;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Http\Request;
use JsonSerializable;

/**
 * @OA\Schema(
 *     properties={
 *          @OA\Property(
 *              property="data",
 *              type="object",
 *                  @OA\Property(property="access_token", type="string"),
 *                  @OA\Property(property="account_status", type="string")
 *          )
 *     }
 * )
 */
class AuthResource extends SuccessResource
{
    /**
     * @param Request $request
     * @return array|JsonSerializable|Arrayable
     */
    public function toArray($request): array|JsonSerializable|Arrayable
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
