<?php

namespace Modules\Admin\Transformers;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Http\Request;
use JsonSerializable;

class FailResource extends Resource
{
    /**
     * SuccessResource constructor.
     * @param null $resource
     * @param int $code
     * @param string $message
     */
    public function __construct($resource = null, $code = 404, string $message = "Error")
    {
        parent::__construct($resource, new MetaResource($code, $message, ['a' => 'b']));
    }

    /**
     * @param mixed|array['httpCode']|array['httpMessage'] ...$meta
     * @return FailResource
     */
    public static function make(...$meta): static
    {
        $parent = parent::make(); // TODO: Change the autogenerated stub

        if (isset($meta[0]) && !empty($meta[0])) {
            $parent->meta->code = $meta[0]['httpCode'] ?? $parent->meta->code;
            $parent->meta->message = $meta[0]['httpMessage'] ?? $parent->meta->message;
        }

        return $parent;
    }

    /**
     * @param int $code
     * @return $this
     */
    public function setMetaCode(int $code)
    {
        $this->meta->code = $code;

        return $this;
    }

    /**
     * @param string $message
     * @return mixed
     */
    public function setMetaMessage(string $message)
    {
        $this->meta->message = $message;

        return $this;
    }

    /**
     * Transform the resource into an array.
     *
     * @param Request $request
     * @return array|Arrayable|JsonSerializable
     */
    public function toArray($request): array|JsonSerializable|Arrayable
    {
        return parent::toArray($request);
    }
}
